version: '3.8'

services:
  mysql_auth:
    image: mysql:8
    container_name: mysql_auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql

  auth_service:
    build: ./Backend/auth
    container_name: auth_service
    ports:
      - "8000:8000"
    depends_on:
      - mysql_auth
    environment:
      DB_HOST: mysql_auth
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: auth_db
    volumes:
      - ./Backend/auth:/app
    command: ["bash", "entrypoint.sh"]

volumes:
  auth_db_data:
